version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:80"
    environment:
      - BACKEND_URL=${BACKEND_URL:-https://disclose-heaving-disloyal.ngrok-free.dev}
    container_name: nhcx-cli
    networks:
      - nhcx-service_nhcx_network
    restart: unless-stopped

networks:
  nhcx-service_nhcx_network:
    external: true
