version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:80"
    environment:
      - BACKEND_URL=${BACKEND_URL:-https://disclose-heaving-disloyal.ngrok-free.dev}
    container_name: nhcx-cli
