server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # SPA fallback
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy /nhcx/* to backend — set BACKEND_URL at docker run time
    location /nhcx {
        proxy_pass ${BACKEND_URL};
        proxy_ssl_server_name on;
        proxy_set_header Host $proxy_host;
        proxy_set_header ngrok-skip-browser-warning 69420;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
