server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # SPA fallback
    location /nhcx/frontend/ {
        try_files $uri $uri/ /nhcx/frontend/index.html;
    }
    location /nhcx/backend/api {
        proxy_pass ${BACKEND_URL};
        proxy_set_header Host $proxy_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
